### PR TITLE
Use spawn instead of exec to execute command (Fixes #171)

### LINKED ISSUE #171: Incomplete output displayed and [Done] exited with code=null
When running a program with lots of console output, I'm getting a "[Done] exited with code=null in 0.0XX seconds" before all of the output has actually been written to the console.

Below is a simple Python3 example to reproduce the problem. Each time the code is run, the console output will enumerate to a different count value before it stops with the code=null exit code.

```
for count in range(100000):
    print(count)
```

The output window displays...

```
...
37345
37346
37347
37348
37349
37
[Done] exited with code=null in 0.044 seconds
```

If I run the same example in the Visual Studio Code terminal window, the full expected output is displayed every time.

### PR DESCRIPTION
**Pull request by JeffreyCA**
Fixes #171 

The following Python code now runs to completion without having to set `runInTerminal` to `true`.
```py
for count in range(100000):
    print(count)
```

When using `spawn`, the stdout and stderr `data` object is a `uint8array` so it needs to be decoded into a string before appending to the output channel.

### CODE REVIEW

File: src/codeManager.ts [hunk 1]
```diff
@@ -451,21 +451,24 @@ export class CodeManager implements vscode.Disposable {
...
         const startTime = new Date();
-        this._process = exec(command, { cwd: this._cwd });
+        this._process = spawn(command, [], { cwd: this._cwd, shell: true });
+
+        const TextDecoder = require("util").TextDecoder;
+        const decoder = new TextDecoder();
 
         this._process.stdout.on("data", (data) => {
-            this._outputChannel.append(data);
+            this._outputChannel.append(decoder.decode(data));
```
Comment (formulahendry) [inline src/codeManager.ts]: What's the difference between `decoder.decode(data)` and `data.toString()`? Others look good to me!

Comment (JeffreyCA) [reply src/codeManager.ts]: Calling `toString()` on `data` (a `uint8array`) results in a string representation of the int array, not the actual decoded value.

Also see [this](https://stackoverflow.com/a/36949791/2789451)

Comment (formulahendry) [reply src/codeManager.ts]: Seems like the official doc also use `data.toString()` :https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options
And I have tried `data.toString()`, the output is the same `decoder.decode(data)`. Just want to know if there is any case needed to use `decoder.decode(data)`, since `data.toString()` would be simple.

Comment (JeffreyCA) [reply src/codeManager.ts]: You're right, this was a couple of months ago so I don't remember exactly why I used TextDecoder. I have made the change.

**Comment by formulahendry** [comment]
Thanks @JeffreyCA !
